### ISSUE TITLE
Slight change needed to your DIY instructions

### ISSUE THREAD

**Issue by dasmb** [eirslett/kubectl-windows#1]
Following your DIY instructions (no hate intended but I don't run random EXEs I find on github, my IT guys would kill me. Besides I'd like 1.1.7 support).

At step 6, instructions should read

`cd C:\gopath\src\k8s.io\kubernetes\`

(using correct path for godep to do its thang)

Thanks much for the instructions _and_ the binary (even though I didn't use it)!

**Comment by eirslett** [comment]
You're welcome! I promise, I didn't pack a bitcoin miner into the binary :wink: Thanks for the correction!
