### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by LeiYangGH** [eirslett/kubectl-windows#6]
Is this project still under maintainance?
I downloaded the latest version:

$ ./kubectl.exe  version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"windows/amd64"}

and run a command
**./kubectl.exe  --context qa-develop  get nodes**

which can run less than 0.1 second in linux version.
but the windows version takes **55** seconds!

I attached the logs, could you have a look?

**Comment by LeiYangGH** [comment]
[kubectl.windows.log](https://github.com/eirslett/kubectl-windows/files/2326231/kubectl.windows.log)

**Comment by eirslett** [comment]
Kubernetes distributes its own Windows binaries now:

https://storage.googleapis.com/kubernetes-release/release/v1.11.0/bin/windows/amd64/kubectl.exe
